// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD_xcDDh9hllrRogSXC2MjCyGl9DR_2OU',
    appId: '1:37981972803:web:aa81d52aca1b3837bca7f6',
    messagingSenderId: '37981972803',
    projectId: 'billfie-dev',
    authDomain: 'billfie-dev.firebaseapp.com',
    storageBucket: 'billfie-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH9mddjeixaUZL7dN8PFG5lI57JBT_Me4',
    appId: '1:37981972803:android:53e04e1d18a42f8abca7f6',
    messagingSenderId: '37981972803',
    projectId: 'billfie-dev',
    storageBucket: 'billfie-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKFhlLepSC3V5yuvfSjh01OtbveHrXiVM',
    appId: '1:37981972803:ios:6f1c9b76f76878edbca7f6',
    messagingSenderId: '37981972803',
    projectId: 'billfie-dev',
    storageBucket: 'billfie-dev.firebasestorage.app',
    iosClientId: '37981972803-14bo0e6ajnjocsjdg9tgkoq5rnvoosjg.apps.googleusercontent.com',
    iosBundleId: 'com.billfie.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKFhlLepSC3V5yuvfSjh01OtbveHrXiVM',
    appId: '1:37981972803:ios:e1ae58b5d0513429bca7f6',
    messagingSenderId: '37981972803',
    projectId: 'billfie-dev',
    storageBucket: 'billfie-dev.firebasestorage.app',
    iosClientId: '37981972803-67v4ugkinkn31hkietutgcj3t2l239di.apps.googleusercontent.com',
    iosBundleId: 'com.example.splittingSucks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD_xcDDh9hllrRogSXC2MjCyGl9DR_2OU',
    appId: '1:37981972803:web:aa81d52aca1b3837bca7f6',
    messagingSenderId: '37981972803',
    projectId: 'billfie-dev',
    authDomain: 'billfie-dev.firebaseapp.com',
    storageBucket: 'billfie-dev.firebasestorage.app',
  );
}
